name: Build LaTeX document
on: [pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Compilation
        uses: vinay0410/tectonic-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tex_path: 'master.tex'
